export type ClawErrorCode =
  | "PROJECT_ROOT_NOT_FOUND"
  | "CLAW_DIR_NOT_FOUND"
  | "PLAN_CREATE_SCOPE_DECISION_REQUIRED"
  | "PROJECT_ALREADY_INITIALIZED"
  | "PROJECT_CONFIG_INVALID"
  | "TASK_NOT_FOUND"
  | "TASK_NAME_INVALID"
  | "ACTIVE_PLAN_INVALID"
  | "ACTIVE_PLAN_MISSING"
  | "PLAN_NOT_FOUND"
  | "PLAN_ALREADY_EXISTS"
  | "PLAN_STATUS_INVALID"
  | "PLAN_STATUS_NOT_SETTABLE"
  | "PLAN_STATUS_TRANSITION_FORBIDDEN"
  | "PLAN_STATUS_REOPEN_REQUIRED"
  | "TASK_STATUS_FORBIDDEN_IN_NON_ACTIVE_PLAN"
  | "PLAN_WRITE_CONFLICT"
  | "PLAN_STALE_EDIT"
  | "PLAN_CREATE_BLOCKED_BY_PROCESS_PLAN"
  | "CURRENT_PLAN_REQUIRED"
  | "PLAN_NOT_RESUMABLE"
  | "PLAN_FOCUS_CONFLICT"
  | "PLAN_TRANSITION_CONFLICT"
  | "FOCUS_RECOVERY_CONFLICT"
  | "SESSION_IDENTITY_INVALID"
  | "SESSION_NOT_FOUND"
  | "SESSION_EXPIRED"
  | "SESSION_PROTOCOL_UNSUPPORTED"
  | "SESSION_COMMAND_FAILED"
  | "SESSION_OPERATION_UNSUPPORTED"
  | "RETROSPECTIVE_REQUIRED"
  | "MEMORY_QUERY_REQUIRED"
  | "MEMORY_DISABLED"
  | "MEMORY_STORE_BUSY"
  | "MEMORY_VECTOR_INDEX_REQUIRED"
  | "GITNEXUS_REFRESH_FAILED"
  | "KNOWLEDGE_DIRECT_WORKFLOW_ACTIVE"
  | "KNOWLEDGE_DIRECT_CONFIG_CHANGED"
  | "KNOWLEDGE_DIRECT_RESOURCE_MISSING"
  | "KNOWLEDGE_DIRECT_PATH_INVALID"
  | "TRUTH_TARGET_INVALID"
  | "INPUT_REQUIRED";

export class ClawError extends Error {
  readonly code: ClawErrorCode;
  readonly details: Record<string, unknown> | undefined;

  constructor(code: ClawErrorCode, message: string, details?: Record<string, unknown>) {
    super(message);
    this.name = "ClawError";
    this.code = code;
    this.details = details;
  }
}
