window.__ModuleLoader__.load({
  id: "@veewo/dsh-claw-kit",
  factory: (require) => {
    const React = require("react");
    const jsx = require("react/jsx-runtime");
    const inject = ["slots", "connection"];
    const SECTIONS = [
      { title: "Workflow", rows: [["planning", "Planning", "boolean"], ["autoUpdate", "Automatically update project guidance", "boolean"], ["goalMode", "Goal mode", "boolean"], ["maxTasksToKeep", "Completed tasks to retain", "number"], ["contextPaths", "Additional context paths", "list"], ["gitnexus", "GitNexus", "boolean"]] },
      { title: "Knowledge writer", rows: [["knowledgeWriter.executionPolicy", "Execution policy", "policy"], ["knowledgeWriter.model", "Model", "text"], ["knowledgeWriter.reasoningEffort", "Reasoning effort", "effort"]] },
      { title: "Memory", rows: [["memory.enabled", "Enabled", "boolean"], ["memory.autoUpdate", "Automatically update", "boolean"], ["memory.externalDocPaths", "External document paths", "list"]] },
    ];
    const ALL_ROWS = SECTIONS.flatMap((section) => section.rows.map(([key, label, kind]) => ({ key, label, kind, section: section.title })));
    function ProjectConfigSection({ call }) {
      const [items, setItems] = React.useState([]), [workspaceId, setWorkspaceId] = React.useState(""), [rows, setRows] = React.useState([]), [editing, setEditing] = React.useState(), [status, setStatus] = React.useState("Loading projects…"); const request = React.useRef(0);
      const invoke = async (endpoint, payload) => { const result = await call(endpoint, payload); if (!result || result.ok !== true) throw new Error(result?.error?.message || "Request failed."); return result.value; };
      const loadRows = async (id) => { if (!id) return; const requestId = ++request.current; try { const snapshots = await Promise.all(ALL_ROWS.map(async (definition) => ({ definition, team: await invoke("get", { workspaceId: id, layer: "team", key: definition.key }), personal: await invoke("get", { workspaceId: id, layer: "personal", key: definition.key }) }))); if (requestId !== request.current) return; setRows(snapshots.map(({ definition, team, personal }) => ({ ...definition, team, personal, effective: personal.effectivePresent ? personal.effectiveValue : undefined }))); setStatus("Project configuration loaded."); } catch (error) { if (requestId === request.current) setStatus(error.message); } };
      React.useEffect(() => { void (async () => { try { const listed = await invoke("list", {}), next = Array.isArray(listed?.items) ? listed.items : [], id = next[0]?.workspaceId || ""; setItems(next); setWorkspaceId(id); if (id) await loadRows(id); else setStatus("No registered claw-kit projects."); } catch (error) { setStatus(error.message); } })(); }, []);
      const display = (value, present, inherit) => !present ? (inherit ? "−" : "Not set") : value === null ? "null" : Array.isArray(value) ? (value.length ? value.join(", ") : "None") : String(value);
      const draftFor = (row, layer) => { const snapshot = row[layer], value = snapshot.present ? snapshot.value : row.effective; if (row.kind === "list") return Array.isArray(value) ? value.join("\n") : ""; return value === null || value === undefined ? "" : String(value); };
      const beginEdit = (row, layer) => setEditing({ key: row.key, layer, draft: draftFor(row, layer), nullValue: row[layer].present && row[layer].value === null, revision: row[layer].revision, error: "" });
      const parse = (row, draft, nullValue) => { if (nullValue) return null; if (row.kind === "boolean") return draft === "true"; if (row.kind === "number") { const value = Number(draft); if (!Number.isFinite(value)) throw new Error("Enter a valid number."); return value; } if (row.kind === "list") return draft.split(/\r?\n/).map((item) => item.trim()).filter(Boolean); return draft; };
      const apply = async (row) => { if (!editing) return; try { const value = parse(row, editing.draft, editing.nullValue); await invoke("set", { workspaceId, layer: editing.layer, key: row.key, value, revision: editing.revision }); setEditing(undefined); await loadRows(workspaceId); setStatus("Saved."); } catch (error) { try { const latest = await invoke("get", { workspaceId, layer: editing.layer, key: row.key }); setEditing({ ...editing, revision: latest.revision, error: latest.revision !== editing.revision ? "This value changed elsewhere. Review your draft, then apply it again." : error.message }); } catch { setEditing({ ...editing, error: error.message }); } } };
      const restoreInheritance = async (row) => { try { await invoke("unset", { workspaceId, layer: "personal", key: row.key, revision: row.personal.revision }); setEditing(undefined); await loadRows(workspaceId); setStatus("Personal override removed; the team value now applies."); } catch (error) { setEditing({ ...(editing || { key: row.key, layer: "personal", draft: "", nullValue: false }), error: error.message }); } };
      const control = (row) => { if (!editing) return null; const set = (patch) => setEditing({ ...editing, ...patch, error: "" }); if (row.kind === "boolean") return jsx.jsxs("select", { value: editing.draft, onChange: (event) => set({ draft: event.target.value, nullValue: false }), children: [jsx.jsx("option", { value: "true", children: "Enabled" }), jsx.jsx("option", { value: "false", children: "Disabled" })] }); if (row.kind === "policy") return jsx.jsxs("select", { value: editing.draft, onChange: (event) => set({ draft: event.target.value, nullValue: false }), children: ["background", "main-agent", "subagent"].map((value) => jsx.jsx("option", { value, children: value }, value)) }); if (row.kind === "effort") return jsx.jsxs("select", { value: editing.draft, onChange: (event) => set({ draft: event.target.value, nullValue: false }), children: ["minimal", "low", "medium", "high", "xhigh"].map((value) => jsx.jsx("option", { value, children: value }, value)) }); return jsx.jsx(row.kind === "list" ? "textarea" : "input", { value: editing.draft, rows: row.kind === "list" ? 3 : undefined, type: row.kind === "number" ? "number" : "text", onChange: (event) => set({ draft: event.target.value, nullValue: false }), placeholder: row.kind === "list" ? "One path per line" : "Value" }); };
      const cell = (row, layer) => { const snapshot = row[layer], active = editing?.key === row.key && editing?.layer === layer; const cellStyle = { padding: "10px 12px", borderTop: "1px solid rgba(127,127,127,.18)", verticalAlign: "top" }; if (active) return jsx.jsxs("td", { style: cellStyle, children: [control(row), row.kind !== "boolean" && jsx.jsxs("label", { style: { display: "block", marginTop: 4 }, children: [jsx.jsx("input", { type: "checkbox", checked: editing.nullValue, onChange: (event) => setEditing({ ...editing, nullValue: event.target.checked, error: "" }) }), " Store null"] }), jsx.jsxs("div", { style: { marginTop: 6 }, children: [jsx.jsx("button", { onClick: () => apply(row), children: "Apply" }), " ", jsx.jsx("button", { onClick: () => setEditing(undefined), children: "Cancel" }), layer === "personal" && snapshot.present && jsx.jsx("button", { onClick: () => restoreInheritance(row), style: { marginLeft: 8 }, children: "Restore inheritance" })] }), editing.error && jsx.jsx("small", { style: { color: "#c33" }, children: editing.error })] }); const inherited = layer === "personal" && !snapshot.present; return jsx.jsx("td", { style: cellStyle, children: jsx.jsx("button", { title: inherited ? "Inherited from team configuration" : "Edit value", onClick: () => beginEdit(row, layer), style: { background: inherited ? "transparent" : "rgba(127,127,127,.06)", border: 0, borderRadius: 5, color: inherited ? "#888" : "inherit", minWidth: inherited ? 20 : undefined, padding: inherited ? "2px 4px" : "4px 7px", textAlign: "left", cursor: "pointer" }, children: display(snapshot.value, snapshot.present, layer === "personal") }) }); };
      return jsx.jsxs("section", { style: { display: "grid", gap: 20, maxWidth: 1100, padding: 12 }, children: [jsx.jsx("p", { style: { color: "#777", margin: 0 }, children: "Project values are stored only in .claw/project.json (team) and .claw/project-override.json (personal). Click a value to edit it." }), jsx.jsx("select", { style: { maxWidth: 420, padding: "7px 9px" }, value: workspaceId, onChange: (event) => { setWorkspaceId(event.target.value); setEditing(undefined); void loadRows(event.target.value); }, children: items.map((item) => jsx.jsx("option", { value: item.workspaceId, children: item.title }, item.workspaceId)) }), SECTIONS.map((section) => jsx.jsxs("section", { style: { border: "1px solid rgba(127,127,127,.22)", borderRadius: 9, overflow: "hidden" }, children: [jsx.jsx("h3", { style: { background: "rgba(127,127,127,.07)", fontSize: 14, margin: 0, padding: "10px 12px" }, children: section.title }), jsx.jsxs("table", { style: { width: "100%", borderCollapse: "collapse", tableLayout: "fixed" }, children: [jsx.jsx("thead", { children: jsx.jsxs("tr", { children: [jsx.jsx("th", { style: { textAlign: "left", padding: "8px 12px", fontSize: 12, color: "#777" }, children: "Setting" }), jsx.jsx("th", { style: { textAlign: "left", padding: "8px 12px", fontSize: 12, color: "#777" }, children: "Team configuration" }), jsx.jsx("th", { style: { textAlign: "left", padding: "8px 12px", fontSize: 12, color: "#777" }, children: "Personal override" }), jsx.jsx("th", { style: { textAlign: "left", padding: "8px 12px", fontSize: 12, color: "#777" }, children: "Effective value" })] }) }), jsx.jsx("tbody", { children: rows.filter((row) => row.section === section.title).map((row) => jsx.jsxs("tr", { children: [jsx.jsx("td", { style: { padding: "10px 12px", borderTop: "1px solid rgba(127,127,127,.18)", fontWeight: 500, verticalAlign: "top" }, children: row.label }), cell(row, "team"), cell(row, "personal"), jsx.jsx("td", { style: { padding: "10px 12px", borderTop: "1px solid rgba(127,127,127,.18)", verticalAlign: "top" }, children: display(row.effective, row.personal.effectivePresent, false) })] }, row.key)) })] })] }, section.title)), jsx.jsx("small", { children: status })] });
    }
    function apply(ctx) { const call = (endpoint, payload) => ctx.connection.rpc.call("/claw-project-config", endpoint, payload); ctx.slots.inject("settings.section", () => ctx.slots.register({ name: "settings.section", id: "claw-kit", order: 40, label: () => "Claw Kit", inject: () => ({ call }) }, ProjectConfigSection)); }
    return { inject, apply };
  },
});
